trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  acrName: sprjtodoappcr
  imageName: todo-frontend
  tag: $(Build.BuildId)

steps:
  - task: NodeTool@0
    displayName: 'Instalar Node.js'
    inputs:
      versionSpec: '20.x'

  - task: Docker@2
    displayName: 'Build e Push da imagem'
    inputs:
      containerRegistry: 'acr-connection'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        $(tag)
        latest