trigger:
  paths:
    include:
      - todo-frontend/*

pool:
  name: Default

variables:
  acrName: sprjacrshared
  imageName: todo-frontend
  dateTag: $[format('{0:yyyy}{0:MM}{0:dd}-{0:HH}{0:mm}', pipeline.startTime)]

steps:
  - task: NodeTool@0
    displayName: 'Instalar Node.js'
    inputs:
      versionSpec: '20.x'

  - task: Docker@2
    displayName: 'Build e Push da imagem'
    inputs:
      containerRegistry: 'acr-connection'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'todo-frontend/Dockerfile'
      tags: |
        $(dateTag)
        latest