trigger:
  paths:
    include:
      - todo-backend/*

pool:
  name: Default

variables:
  - group: todo-app-secrets
  - name: acrName
    value: sprjacr                          
  - name: imageName
    value: todo-backend
  - name: dateTag
    value: $[format('{0:yyyy}{0:MM}{0:dd}-{0:HH}{0:mm}', pipeline.startTime)]

steps:
  - pwsh: |
      $privateKeyBytes = [Convert]::FromBase64String($env:JWT_PRIVATE_KEY)
      $privateKey = [System.Text.Encoding]::UTF8.GetString($privateKeyBytes)
      Set-Content -Path "todo-backend/src/main/resources/privateKey.pem" -Value $privateKey -NoNewline

      $publicKeyBytes = [Convert]::FromBase64String($env:JWT_PUBLIC_KEY)
      $publicKey = [System.Text.Encoding]::UTF8.GetString($publicKeyBytes)
      Set-Content -Path "todo-backend/src/main/resources/publicKey.pem" -Value $publicKey -NoNewline
    displayName: 'Criar arquivos PEM'
    env:
      JWT_PRIVATE_KEY: $(JWT_PRIVATE_KEY)
      JWT_PUBLIC_KEY: $(JWT_PUBLIC_KEY)
    
  - task: Maven@4
    displayName: 'Build Quarkus'
    inputs:
      mavenPomFile: 'todo-backend/pom.xml'
      goals: 'package'
      options: '-DskipTests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.25'

  - task: Docker@2
    displayName: 'Build e Push da imagem'
    inputs:
      containerRegistry: 'sprjacr-connection'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'todo-backend/Dockerfile'
      tags: |
        $(dateTag)
        latest
    env:
      DOCKER_BUILDKIT: 0

  - task: AzureCLI@2
    displayName: 'Deploy no Container App — Backend'
    inputs:
      azureSubscription: 'azure-connection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az containerapp update `
          --name sprj-ca-todo-app `           
          --resource-group sprj-rg `          
          --image sprjacr.azurecr.io/todo-backend:$(dateTag)  