trigger:
  paths:
    include:
      - todo-backend/*

pool:
  name: Default

variables:
  acrName: sprjacrshared
  imageName: todo-backend
  dateTag: $[format('{0:yyyy}{0:MM}{0:dd}-{0:HH}{0:mm}', pipeline.startTime)]

steps:
  - task: Maven@4
    displayName: 'Build Quarkus'
    inputs:
      mavenPomFile: 'todo-backend/pom.xml'
      goals: 'package'
      options: '-DskipTests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.25'

  - task: Docker@2
    displayName: 'Build e Push da imagem'
    inputs:
      containerRegistry: 'acr-connection'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'todo-backend/Dockerfile'
      tags: |
        $(dateTag)
        latest
    env:
      DOCKER_BUILDKIT: 0