# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=todo
quarkus.datasource.password=todo123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tododb

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# JWT
mp.jwt.verify.issuer=https://todoapp.com
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem