# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=todo
quarkus.datasource.password=todo123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tododb

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# JWT
mp.jwt.verify.issuer=https://todoapp.com
quarkus.smallrye-jwt.enabled=true

# Chave para assinar o token
smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}
smallrye.jwt.sign.key-format=PKCS8
mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}

# CORS
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type
quarkus.http.cors.exposed-headers=Authorization